export const CARS_DATA = [
  {
    "id": "001",
    "name": "G63",
    "fullName": "Mercedes-AMG G63 (W464)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "14,800 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "9-Speed AMG SPEEDSHIFT",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "577 hp",
    "torque": "850 Nm",
    "img": "https://cdn.prod.website-files.com/63e417c5087e0d4f29c23689/68532ca46fa81ca8aea8c8b9_DSC02195.jpg",
    "desc": "Pristine condition Mercedes-AMG G63 sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "002",
    "name": "G500",
    "fullName": "Mercedes-Benz G500 AMG Line (W464)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "22,300 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "422 hp",
    "torque": "610 Nm",
    "img": "https://images.kb-qatar.com/10036/188c/knightsbridge-automotive-lg.jpg",
    "desc": "Pristine condition Mercedes-Benz G500 AMG Line sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "003",
    "name": "GLE63",
    "fullName": "Mercedes-AMG GLE 63 S 4MATIC+",
    "brand": "mercedes",
    "year": 2022,
    "mileage": "16,900 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9-Speed AMG SPEEDSHIFT TCT",
    "drivetrain": "4MATIC+ All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "603 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/1/19/Mercedes-AMG_GLE_63_S_4MATIC_IMG_3430.jpg",
    "desc": "Pristine condition Mercedes-AMG GLE 63 S sourced with verified history.",
    "isSpecial": false
  },
  {
  "id": "004",
  "name": "GLE63",
  "fullName": "Mercedes-AMG GLE 63 S Coupe",
  "brand": "mercedes",
  "year": 2023,
  "mileage": "9,400 KM",
  "engine": "4.0L Twin-Turbo V8 + EQ Boost",
  "transmission": "9-Speed AMG SPEEDSHIFT TCT",
  "drivetrain": "4MATIC+ All-Wheel Drive",
  "fuelType": "Petrol/Hybrid",
  "power": "603 hp",
  "torque": "850 Nm",
  "img": "https://cdn-ds.com/blogs-media/sites/178/2023/04/21044836/2023_Mercedes-AMG_GLE_63_S_Coupe_Edition-55_A_o.jpg",
  "desc": "Pristine condition Mercedes-AMG GLE 63 S Coupe sourced with verified history.",
  "isSpecial": false
},
  {
    "id": "005",
    "name": "VOGUE",
    "fullName": "Range Rover Autobiography P550 PHEV (L460)",
    "brand": "landrover",
    "year": 2023,
    "mileage": "7,200 KM",
    "engine": "4.4L Twin-Turbo V8 + Electric Motor",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol/Plug-in Hybrid",
    "power": "550 hp",
    "torque": "750 Nm",
    "img": "https://canadianautoreview.ca/wp-content/uploads/2025/09/rr-phev-09.jpg",
    "desc": "Pristine condition Range Rover Autobiography sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "006",
    "name": "GT-R",
    "fullName": "Nissan GT-R Nismo (R35)",
    "brand": "nissan",
    "year": 2022,
    "mileage": "8,200 KM",
    "engine": "3.8L Twin-Turbo V6 (VR38DETT)",
    "transmission": "6-Speed Dual-Clutch",
    "drivetrain": "ATTESA E-TS AWD",
    "fuelType": "Petrol",
    "power": "600 hp",
    "torque": "652 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/01/Nissan_GT-R_Nismo_%28R35%29%2C_2022%2C_rear.jpg",
    "desc": "Pristine condition Nissan GT-R Nismo sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "007",
    "name": "GT-R",
    "fullName": "Nissan GT-R Nismo Special Edition (R35)",
    "brand": "nissan",
    "year": 2022,
    "mileage": "5,600 KM",
    "engine": "3.8L Twin-Turbo V6 (VR38DETT)",
    "transmission": "6-Speed Dual-Clutch",
    "drivetrain": "ATTESA E-TS AWD",
    "fuelType": "Petrol",
    "power": "600 hp",
    "torque": "652 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Osaka_Auto_Messe_2022_%2837%29_-_Nissan_GT-R_NISMO_Special_Edition_Mid-year_2022.jpg",
    "desc": "Pristine condition Nissan GT-R Nismo Special Edition sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "008",
    "name": "STI",
    "fullName": "Subaru WRX STI EJ20 Final Edition",
    "brand": "subaru",
    "year": 2019,
    "mileage": "11,300 KM",
    "engine": "2.0L Turbocharged Boxer (EJ20)",
    "transmission": "6-Speed Close-Ratio Manual",
    "drivetrain": "Symmetrical AWD with DCCD",
    "fuelType": "Petrol",
    "power": "308 hp",
    "torque": "422 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Osaka_Motor_Show_2019_%2822%29_-_Subaru_WRX_STI_EJ20_Final_Edition_%28CBA-VAB%29.jpg",
    "desc": "Pristine condition Subaru WRX STI EJ20 Final Edition sourced with verified history. Last of the EJ20 turbo flat-fours — a genuine collector's variant.",
    "isSpecial": false
  },
  {
    "id": "009",
  "name": "X5M",
  "fullName": "BMW X5 M Competition (G05)",
  "brand": "bmw",
  "year": 2022,
  "mileage": "14,100 KM",
  "engine": "4.4L Twin-Turbo V8",
  "transmission": "8-Speed M Steptronic",
  "drivetrain": "M xDrive AWD",
  "fuelType": "Petrol",
  "power": "617 hp",
  "torque": "750 Nm",
  "img": "https://images.unsplash.com/photo-1603189617530-6d32306f57c5?q=80&w=988&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "desc": "Pristine condition BMW X5 M Competition sourced with verified history.",
  "isSpecial": false
  },
  {
    "id": "010",
    "name": "CAYENNE",
    "fullName": "Porsche Cayenne Coupe Turbo",
    "brand": "porsche",
    "year": 2021,
    "mileage": "19,600 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Tiptronic S",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "541 hp",
    "torque": "770 Nm",
    "img": "https://assets.autobuzz.my/wp-content/uploads/2021/06/30122833/2021-Porsche-Cayenne-Turbo-GT-11.jpg",
    "desc": "Pristine condition Porsche Cayenne Coupe Turbo sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "011",
    "name": "RUBICON",
    "fullName": "Jeep Wrangler Rubicon 4xe (JL)",
    "brand": "jeep",
    "year": 2022,
    "mileage": "13,700 KM",
    "engine": "2.0L Turbo I4 Plug-in Hybrid",
    "transmission": "8-Speed Automatic",
    "drivetrain": "Rock-Trac 4x4 System",
    "fuelType": "Petrol/Plug-in Hybrid",
    "power": "375 hp",
    "torque": "637 Nm",
    "img": "https://media.ed.edmunds-media.com/jeep/wrangler-4xe/2022/oem/2022_jeep_wrangler-4xe_convertible-suv_unlimited-high-altitude_fq_oem_2_1600.jpg",
    "desc": "Pristine condition Jeep Wrangler Rubicon 4xe sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "012",
    "name": "GOLF R",
    "fullName": "Volkswagen Golf R 333 Limited Edition (Mk8)",
    "brand": "volkswagen",
    "year": 2022,
    "mileage": "9,800 KM",
    "engine": "2.0L Turbo I4 (EA888 Gen 4)",
    "transmission": "7-Speed DSG Dual-Clutch",
    "drivetrain": "4MOTION AWD with Torque Vectoring",
    "fuelType": "Petrol",
    "power": "333 hp",
    "torque": "420 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Volkswagen_Golf_VIII_R_333_Limited_Edition_IMG_9486.jpg",
    "desc": "Pristine condition Volkswagen Golf R 333 Limited Edition sourced with verified history. One of 333 units built worldwide.",
    "isSpecial": false
  },
  {
    "id": "013",
    "name": "HILUX",
    "fullName": "Toyota Hilux GR Sport 2.8 Double Cab",
    "brand": "toyota",
    "year": 2024,
    "mileage": "6,800 KM",
    "engine": "2.8L Turbo Diesel",
    "transmission": "6-Speed Automatic",
    "drivetrain": "Part-Time 4WD",
    "fuelType": "Diesel",
    "power": "204 hp",
    "torque": "500 Nm",
    "img": "https://images.unsplash.com/photo-1663576268373-0bef1214f700?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8MjAyNCUyMCUyRiUyRiUyMDYlMkM4MDAlMjBLTSUyMFRveW90YSUyMEhpbHV4JTIwR1IlMjBTcG9ydCUyMDIuOCUyMERvdWJsZSUyMENhYnxlbnwwfHwwfHx8MA%3D%3D",
    "desc": "Pristine condition Toyota Hilux GR Sport sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "014",
    "name": "M5",
    "fullName": "BMW M5 Competition (F90)",
    "brand": "bmw",
    "year": 2022,
    "mileage": "9,200 KM",
    "engine": "4.4L Twin-Turbo V8",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "M xDrive AWD",
    "fuelType": "Petrol",
    "power": "617 hp",
    "torque": "750 Nm",
    "img": "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition BMW M5 Competition sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "015",
    "name": "LX100",
    "fullName": "Toyota Land Cruiser 100 VXR (J100)",
    "brand": "toyota",
    "year": 2006,
    "mileage": "112,400 KM",
    "engine": "4.7L Petrol V8 (2UZ-FE)",
    "transmission": "5-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "235 hp",
    "torque": "427 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/94/Toyota_Land_Cruiser_100_50th_Anniversary_front.JPG",
    "desc": "Pristine condition Toyota Land Cruiser 100 VXR sourced with verified history. The legendary, bulletproof workhorse — kept as a special listing outside the standard 2019+ lineup.",
    "isSpecial": true
  },
  {
    "id": "016",
    "name": "SVR",
    "fullName": "Range Rover Sport SVR (L494)",
    "brand": "landrover",
    "year": 2015,
    "mileage": "46,800 KM",
    "engine": "5.0L Supercharged V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "543 hp",
    "torque": "680 Nm",
    "img": "https://assets.carandclassic.com/uploads/new/31918174/2023-land-rover-range-rover-sport-6a2cd67d1b2a7.jpg?fit=crop&h=600&ixlib=php-4.1.0&q=85&w=800&s=344e82d980431a7ecd1f2eafe6707cd3",
    "desc": "Pristine condition Range Rover Sport SVR sourced with verified history. Kept as a special listing outside the standard 2019+ lineup.",
    "isSpecial": true
  },
  {
    "id": "017",
    "name": "RS6",
    "fullName": "Audi RS6 Avant (C8)",
    "brand": "audi",
    "year": 2022,
    "mileage": "21,400 KM",
    "engine": "4.0L Twin-Turbo V8 + Mild Hybrid",
    "transmission": "8-Speed Tiptronic Automatic",
    "drivetrain": "quattro All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "591 hp",
    "torque": "800 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Osaka_Auto_Messe_2022_(553)_-_Audi_RS6_Avant_(C8)_with_Sound_Station_Audio.jpg",
    "desc": "Pristine condition Audi RS6 Avant sourced with verified history. Show unit, Osaka Auto Messe 2022.",
    "isSpecial": false
  },
  {
    "id": "018",
    "name": "LX600",
    "fullName": "Lexus LX600 F Sport",
    "brand": "lexus",
    "year": 2022,
    "mileage": "10,500 KM",
    "engine": "3.4L Twin-Turbo V6",
    "transmission": "10-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "409 hp",
    "torque": "650 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/a/a4/2022_Lexus_LX600_F_Sport%2C_NYIAS_2022.jpg",
    "desc": "Pristine condition Lexus LX600 F Sport sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "019",
    "name": "911",
    "fullName": "Porsche 911 Carrera S (992)",
    "brand": "porsche",
    "year": 2019,
    "mileage": "12,900 KM",
    "engine": "3.0L Twin-Turbo Flat-6",
    "transmission": "8-Speed PDK Dual-Clutch",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "443 hp",
    "torque": "530 Nm",
    "img": "https://img.cdn.dragon2000.net/C2530/U4005/IMG_48819-large.jpg",
    "desc": "Pristine condition Porsche 911 Carrera S sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "020",
    "name": "M4",
    "fullName": "BMW M4 Competition (G82)",
    "brand": "bmw",
    "year": 2021,
    "mileage": "11,800 KM",
    "engine": "3.0L Twin-Turbo I6 (S58)",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "503 hp",
    "torque": "650 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/92/BMW_M4_%28G82%29_Mint_Green_IAA_2021_1X7A0036.jpg",
    "desc": "Pristine condition BMW M4 Competition sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "021",
    "name": "URUS",
    "fullName": "Lamborghini Urus",
    "brand": "lamborghini",
    "year": 2021,
    "mileage": "8,600 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "641 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/d/d5/IAA_2021%2C_Munich_%28IAA10227%29.jpg",
    "desc": "Pristine condition Lamborghini Urus sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "022",
    "name": "S580",
    "fullName": "Mercedes-Benz S580 4MATIC (W223)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "15,200 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "4MATIC All-Wheel Drive",
    "fuelType": "Petrol",
    "power": "496 hp",
    "torque": "700 Nm",
    "img": "https://images.unsplash.com/photo-1610099610040-ab19f3a5ec35?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8MjAyMSUyMCUyRiUyRiUyMDE1JTJDMjAwJTIwS00lMjBNZXJjZWRlcy1CZW56JTIwUzU4MCUyMDRNQVRJQyUyMChXMjIzKXxlbnwwfHwwfHx8MA%3D%3D",
    "desc": "Pristine condition Mercedes-Benz S580 sourced with verified history. IAA Munich 2021 show unit.",
    "isSpecial": false
  },
  {
    "id": "023",
    "name": "GLS",
    "fullName": "Mercedes-Benz GLS 580 4MATIC (X167)",
    "brand": "mercedes",
    "year": 2019,
    "mileage": "18,300 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "4MATIC All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "483 hp",
    "torque": "700 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/08/Mercedes-Benz_GLS_%28X167%29_%2848819993208%29.jpg",
    "desc": "Pristine condition Mercedes-Benz GLS 580 sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "024",
    "name": "PANAMERA",
    "fullName": "Porsche Panamera Turbo",
    "brand": "porsche",
    "year": 2019,
    "mileage": "17,600 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed PDK Dual-Clutch",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "550 hp",
    "torque": "770 Nm",
    "img": "https://cdn.elferspot.com/wp-content/uploads/2026/01/07/imgi_108_b503749a-0156-4adc-9db0-8aeb39c77a66.jpeg?class=xl",
    "desc": "Pristine condition Porsche Panamera Turbo sourced with verified history.",
    "isSpecial": false
  },
  {
    "id": "025",
    "name": "BENTAYGA",
    "fullName": "Bentley Bentayga W12",
    "brand": "bentley",
    "year": 2018,
    "mileage": "24,600 KM",
    "engine": "6.0L Twin-Turbo W12",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "600 hp",
    "torque": "900 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/01/2018_Bentley_Bentayga_au_SIAM_2018.JPG",
    "desc": "Pristine condition Bentley Bentayga W12 sourced with verified history. Show unit, Montreal International Auto Show 2018.",
    "isSpecial": false
  },
  {
    "id": "026",
    "name": "BENTAYGA",
    "fullName": "Bentley Bentayga V8",
    "brand": "bentley",
    "year": 2018,
    "mileage": "19,200 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "542 hp",
    "torque": "770 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/a/af/2018-03-06_Geneva_Motor_Show_2409.JPG",
    "desc": "Pristine condition Bentley Bentayga V8 sourced with verified history. Show unit, Geneva International Motor Show 2018.",
    "isSpecial": false
  },

  // ─── BATCH 5 ─────────────────────────────────────────────────────────────────

  {
    "id": "027",
    "name": "DEFENDER",
    "fullName": "Land Rover Defender 110 V8 (L663)",
    "brand": "landrover",
    "year": 2023,
    "mileage": "8,900 KM",
    "engine": "5.0L Supercharged V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "518 hp",
    "torque": "625 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/0b/2023_Cleveland_Auto_Show_(52790188855).jpg",
    "desc": "Pristine condition Land Rover Defender 110 V8 sourced with verified history. Show unit, Cleveland Auto Show 2023.",
    "isSpecial": false
  },
  {
    "id": "028",
    "name": "RS Q8",
    "fullName": "Audi RS Q8 (4M)",
    "brand": "audi",
    "year": 2020,
    "mileage": "17,300 KM",
    "engine": "4.0L Twin-Turbo V8 + Mild Hybrid",
    "transmission": "8-Speed Tiptronic",
    "drivetrain": "quattro All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "591 hp",
    "torque": "800 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/4/4a/2020_Audi_RS_Q8_Front_(1).jpg",
    "desc": "Pristine condition Audi RS Q8 sourced with verified history. The most powerful production Audi SUV.",
    "isSpecial": false
  },
  {
    "id": "029",
    "name": "F8",
    "fullName": "Ferrari F8 Tributo",
    "brand": "ferrari",
    "year": 2019,
    "mileage": "6,100 KM",
    "engine": "3.9L Twin-Turbo V8",
    "transmission": "7-Speed F1 Dual-Clutch",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "710 hp",
    "torque": "770 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Ferrari_F8_Tributo,_GIMS_2019,_Le_Grand-Saconnex_(GIMS0993).jpg",
    "desc": "Pristine condition Ferrari F8 Tributo sourced with verified history. Show unit, Geneva International Motor Show 2019.",
    "isSpecial": false
  },
  {
    "id": "030",
    "name": "XM",
    "fullName": "BMW XM Label Red",
    "brand": "bmw",
    "year": 2023,
    "mileage": "5,800 KM",
    "engine": "4.4L Twin-Turbo V8 + Electric Motor",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "M xDrive AWD",
    "fuelType": "Petrol/Plug-in Hybrid",
    "power": "738 hp",
    "torque": "1,000 Nm",
    "img": "https://en.wheelz.me/wp-content/uploads/2025/11/P90503540_lowRes_jerez-de-la-frontera.webp",
    "desc": "Pristine condition BMW XM Label Red sourced with verified history. Limited to 500 units worldwide — the most powerful BMW M production car ever built.",
    "isSpecial": false
  },
  {
    "id": "031",
    "name": "AMG GT",
    "fullName": "Mercedes-AMG GT Black Series (C190)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "4,200 KM",
    "engine": "4.0L Twin-Turbo V8 (M178 LS2)",
    "transmission": "7-Speed AMG SPEEDSHIFT DCT",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "730 hp",
    "torque": "800 Nm",
    "img": "https://i.ytimg.com/vi/dc-qgYeWTlY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAh219v7W5UjVP9ReZMREVfPSavMA",
    "desc": "Pristine condition Mercedes-AMG GT Black Series sourced with verified history. The most powerful naturally aspirated AMG road car.",
    "isSpecial": false
  },
  {
    "id": "032",
    "name": "CONTINENTAL",
    "fullName": "Bentley Continental GT Speed (3rd Gen)",
    "brand": "bentley",
    "year": 2022,
    "mileage": "11,400 KM",
    "engine": "6.0L Twin-Turbo W12",
    "transmission": "8-Speed Dual-Clutch",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "659 hp",
    "torque": "900 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Bentley_Continental_GT_2020_(49384478638).jpg",
    "desc": "Pristine condition Bentley Continental GT Speed sourced with verified history. Grand tourer flagship from Bentley's iconic Continental line.",
    "isSpecial": false
  },
   {
    "id": "033",
    "name": "PRADO",
    "fullName": "Toyota Land Cruiser Prado VX (J250)",
    "brand": "toyota",
    "year": 2024,
    "mileage": "4,200 KM",
    "engine": "2.4L Turbo 4-Cylinder + Electric Motor (T24A-FTS Hybrid)",
    "transmission": "8-Speed Automatic",
    "drivetrain": "Part-Time 4WD with Active Height Control",
    "fuelType": "Petrol/Hybrid",
    "power": "326 hp",
    "torque": "630 Nm",
    "img": "https://images.unsplash.com/photo-1630826362226-a509049bcdbf?q=80&w=2073&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition Toyota Land Cruiser Prado VX sourced with verified history. The all-new J250 generation — reinvented for capability and efficiency.",
    "isSpecial": false
  },
  {
    "id": "034",
    "name": "FORTUNER",
    "fullName": "Toyota Fortuner GR Sport 2.8 4x4",
    "brand": "toyota",
    "year": 2022,
    "mileage": "12,600 KM",
    "engine": "2.8L Turbo Diesel (1GD-FTV)",
    "transmission": "6-Speed Automatic",
    "drivetrain": "Part-Time 4WD",
    "fuelType": "Diesel",
    "power": "204 hp",
    "torque": "500 Nm",
    "img": "https://images.unsplash.com/photo-1639922195938-611119f7f307?q=80&w=2748&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition Toyota Fortuner GR Sport sourced with verified history. GR Sport flagship trim — sport-tuned suspension, GR aero kit, exclusive interior.",
    "isSpecial": false
  },
  {
    "id": "035",
    "name": "PATROL",
    "fullName": "Nissan Patrol Platinum V8 (Y62 Facelift)",
    "brand": "nissan",
    "year": 2021,
    "mileage": "16,800 KM",
    "engine": "5.6L Naturally Aspirated V8 (VK56VD)",
    "transmission": "7-Speed Automatic",
    "drivetrain": "Part-Time 4WD",
    "fuelType": "Petrol",
    "power": "400 hp",
    "torque": "560 Nm",
    "img": "https://images.unsplash.com/photo-1742230285052-8c3b445c01fc?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition Nissan Patrol Platinum sourced with verified history. The most capable full-size SUV in the Middle East — legendary 5.6L V8, flagship Platinum trim.",
    "isSpecial": false
  },
  {
    "id": "036",
    "name": "M3",
    "fullName": "BMW M3 Competition (G80)",
    "brand": "bmw",
    "year": 2021,
    "mileage": "8,900 KM",
    "engine": "3.0L Twin-Turbo Inline-6 (S58)",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "503 hp",
    "torque": "650 Nm",
    "img": "https://images.unsplash.com/photo-1615644190630-c6c6f230a6ed?q=80&w=988&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition BMW M3 Competition sourced with verified history. IAA Munich 2021 debut car — the most powerful M3 ever built to that point.",
    "isSpecial": false
  },
  {
    "id": "037",
    "name": "E63S",
    "fullName": "Mercedes-AMG E63 S 4MATIC+ Estate (W213)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "19,300 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9-Speed AMG SPEEDSHIFT MCT",
    "drivetrain": "4MATIC+ All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "612 hp",
    "torque": "850 Nm",
    "img": "https://richmonds.com.au/wp-content/uploads/2023/10/mercedes-E63-Grey-1.jpg",
    "desc": "Pristine condition Mercedes-AMG E63 S Estate sourced with verified history. The fastest production estate car in the world — 0–100 km/h in 3.4 seconds.",
    "isSpecial": false
  },
  {
    "id": "038",
    "name": "RS5",
    "fullName": "Audi RS5 Sportback (F5)",
    "brand": "audi",
    "year": 2021,
    "mileage": "14,700 KM",
    "engine": "2.9L Twin-Turbo V6 (TFSI)",
    "transmission": "8-Speed Tiptronic",
    "drivetrain": "quattro All-Wheel Drive",
    "fuelType": "Petrol",
    "power": "450 hp",
    "torque": "600 Nm",
    "img": "https://hips.hearstapps.com/mtg-prod/65c57ab7f41f48000804621e/2021-audi-rs5-sportbck-31.jpg",
    "desc": "Pristine condition Audi RS5 Sportback sourced with verified history. The most versatile RS — five-door performance with genuine daily usability.",
    "isSpecial": false
  },
  {
    "id": "039",
    "name": "MACAN",
    "fullName": "Porsche Macan Turbo (95B)",
    "brand": "porsche",
    "year": 2019,
    "mileage": "22,400 KM",
    "engine": "2.9L Twin-Turbo V6",
    "transmission": "7-Speed PDK Dual-Clutch",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "434 hp",
    "torque": "550 Nm",
    "img": "https://www.stuttcars.com/wp-content/uploads/2021/09/porsche_macan_gts_2021_5k-HD-scaled.jpeg",
    "desc": "Pristine condition Porsche Macan Turbo sourced with verified history. Show unit, Geneva International Motor Show 2019.",
    "isSpecial": false
  },
  {
    "id": "040",
    "name": "VELAR",
    "fullName": "Range Rover Velar P400 R-Dynamic SE (L560)",
    "brand": "landrover",
    "year": 2021,
    "mileage": "11,200 KM",
    "engine": "3.0L Turbocharged Inline-6 + Mild Hybrid (P400)",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol/Hybrid",
    "power": "400 hp",
    "torque": "550 Nm",
    "img": "https://www.southeastautoshowroom.com/imagetag/1588/2/l/Used-2021-Land-Rover-Range-Rover-Velar-P400-R-Dynamic-HSE-(SOLD)-1701636177.jpg",
    "desc": "Pristine condition Range Rover Velar P400 sourced with verified history. R-Dynamic SE specification — the boldest, most design-forward Range Rover ever built.",
    "isSpecial": false
  },
  {
    "id": "041",
    "name": "DEFENDER",
    "fullName": "Land Rover Defender 90 V8 (L663)",
    "brand": "landrover",
    "year": 2022,
    "mileage": "7,600 KM",
    "engine": "5.0L Supercharged V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "518 hp",
    "torque": "625 Nm",
    "img": "https://hips.hearstapps.com/hmg-prod/images/2022-land-rover-defender-90-v8-114-1653515465.jpg",
    "desc": "Pristine condition Land Rover Defender 90 V8 sourced with verified history. The short-wheelbase V8 — 0–100 km/h in 5.0 seconds in a Defender body.",
    "isSpecial": false
  },
  {
    "id": "042",
    "name": "HURACAN",
    "fullName": "Lamborghini Huracan EVO",
    "brand": "lamborghini",
    "year": 2019,
    "mileage": "5,400 KM",
    "engine": "5.2L Naturally Aspirated V10",
    "transmission": "7-Speed LDF Dual-Clutch",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "631 hp",
    "torque": "600 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Lamborghini_Hurac%C3%A1n_EVO%2C_GIMS_2019%2C_Le_Grand-Saconnex_%28GIMS0943%29.jpg",
    "desc": "Pristine condition Lamborghini Huracan EVO sourced with verified history. Show unit, Geneva International Motor Show 2019. LDVI predictive dynamics control — the most technically advanced Huracan ever.",
    "isSpecial": false
  },
  {
    "id": "043",
    "name": "C63S",
    "fullName": "Mercedes-AMG C63 S Coupe (C205)",
    "brand": "mercedes",
    "year": 2019,
    "mileage": "18,900 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "7-Speed AMG SPEEDSHIFT MCT",
    "drivetrain": "Rear-Wheel Drive (RWD)",
    "fuelType": "Petrol",
    "power": "510 hp",
    "torque": "700 Nm",
    "img": "https://richmonds.com.au/wp-content/uploads/2024/10/1-11.jpg",
    "desc": "Pristine condition Mercedes-AMG C63 S Coupe sourced with verified history. The last C63 with the legendary 4.0L V8 — a collector's compact AMG.",
    "isSpecial": false
  },
  {
    "id": "044",
    "name": "MAYBACH",
    "fullName": "Mercedes-Maybach GLS 600 4MATIC (X167)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "12,800 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "4MATIC All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "558 hp",
    "torque": "730 Nm",
    "img": "https://images.classic.com/vehicles/ecae2ec8bc022f882ff483a84a5d16bc.jpeg?ar=16%3A9&fit=crop&h=338&w=600",
    "desc": "Pristine condition Mercedes-Maybach GLS 600 sourced with verified history. IAA Munich 2021 show unit. The ultra-luxury SUV — first-class cabin in a full-size 4x4.",
    "isSpecial": false
  },
  {
    "id": "045",
    "name": "RS3",
    "fullName": "Audi RS3 Sportback (8Y)",
    "brand": "audi",
    "year": 2022,
    "mileage": "7,300 KM",
    "engine": "2.5L Five-Cylinder Turbo (TFSI)",
    "transmission": "7-Speed S-Tronic Dual-Clutch",
    "drivetrain": "quattro All-Wheel Drive",
    "fuelType": "Petrol",
    "power": "400 hp",
    "torque": "500 Nm",
    "img": "https://www.bavariamotors.be/img/cars/1rs333.jpg?q=90&s=6c4bf3b693905db2a10a01f04fd104a6",
    "desc": "Pristine condition Audi RS3 Sportback sourced with verified history. The world's most powerful 5-cylinder production car — RS Torque Splitter rear axle for precision torque vectoring.",
    "isSpecial": false
  },
  {
    "id": "046",
    "name": "911TS",
    "fullName": "Porsche 911 Turbo S (992)",
    "brand": "porsche",
    "year": 2020,
    "mileage": "9,100 KM",
    "engine": "3.8L Twin-Turbo Flat-6",
    "transmission": "8-Speed PDK Dual-Clutch",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "641 hp",
    "torque": "800 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Porsche_911_Turbo_S_%28992%29%2C_GIMS_2020%2C_Le_Grand-Saconnex.jpg",
    "desc": "Pristine condition Porsche 911 Turbo S sourced with verified history. Show unit, Geneva International Motor Show 2020. 0–100 km/h in 2.7 seconds — the benchmark sports car.",
    "isSpecial": false
  },
  {
    "id": "047",
    "name": "EVO X",
    "fullName": "Mitsubishi Lancer Evolution X Final Edition (CZ4A)",
    "brand": "mitsubishi",
    "year": 2015,
    "mileage": "38,700 KM",
    "engine": "2.0L Turbocharged Inline-4 (4B11T)",
    "transmission": "5-Speed Twin-Clutch SST",
    "drivetrain": "Super All-Wheel Control (S-AWC)",
    "fuelType": "Petrol",
    "power": "291 hp",
    "torque": "422 Nm",
    "img": "https://images.unsplash.com/photo-1611023939376-e1e16d1c15bd?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "desc": "Pristine condition Mitsubishi Lancer Evolution X Final Edition sourced with verified history. Show unit, Osaka Auto Messe 2015. The last Evo ever built — a motorsport-bred icon and guaranteed future collectible. Kept as a special listing outside the standard 2018+ lineup.",
    "isSpecial": true
  },
  {
    "id": "048",
    "name": "URUS P",
    "fullName": "Lamborghini Urus Performante",
    "brand": "lamborghini",
    "year": 2023,
    "mileage": "3,800 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "666 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Lamborghini_Urus_Performante_%282023%29_front.jpg",
    "desc": "Pristine condition Lamborghini Urus Performante sourced with verified history. 35 kg lighter than the standard Urus, track-focused aero package — the fastest production SUV on the Nürburgring.",
    "isSpecial": false
  }
];
