export const CARS_DATA = [
  {
    "id": "001",
    "name": "G63",
    "fullName": "Mercedes-AMG G63 (W464)",
    "brand": "mercedes",
    "year": 2022,
    "mileage": "14,800 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "9-Speed AMG SPEEDSHIFT",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "577 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/92/Mercedes-AMG_G63_%28W464%29_front.jpg",
    "desc": "Pristine condition Mercedes-AMG G63 sourced with verified history."
  },
  {
    "id": "002",
    "name": "G500",
    "fullName": "Mercedes-Benz G500 AMG Line (W464)",
    "brand": "mercedes",
    "year": 2021,
    "mileage": "22,300 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "422 hp",
    "torque": "610 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Mercedes-Benz_G500_%28W464%29.jpg",
    "desc": "Pristine condition Mercedes-Benz G500 AMG Line sourced with verified history."
  },
  {
    "id": "003",
    "name": "G500",
    "fullName": "Mercedes-Benz G500 Classic (W463)",
    "brand": "mercedes",
    "year": 2017,
    "mileage": "48,600 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "7G-TRONIC Automatic",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "422 hp",
    "torque": "610 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/3/33/Mercedes-Benz_G500_%28W463%29_front.jpg",
    "desc": "Pristine condition Mercedes-Benz G500 sourced with verified history. Lower-mileage entry point into G-Wagon ownership."
  },
  {
    "id": "004",
    "name": "G63",
    "fullName": "Mercedes-Benz G63 AMG Final Edition (W463)",
    "brand": "mercedes",
    "year": 2018,
    "mileage": "39,200 KM",
    "engine": "5.5L Twin-Turbo V8",
    "transmission": "7G-TRONIC Automatic",
    "drivetrain": "Four-Wheel Drive (4WD)",
    "fuelType": "Petrol",
    "power": "563 hp",
    "torque": "760 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/2/22/Mercedes-Benz_W463_FL_G_63_AMG_Polar_White_%281%29.jpg",
    "desc": "Pristine condition Mercedes-Benz G63 AMG sourced with verified history. Last of the outgoing W463 body style."
  },
  {
    "id": "005",
    "name": "GLE63",
    "fullName": "Mercedes-AMG GLE 63 S 4MATIC+",
    "brand": "mercedes",
    "year": 2022,
    "mileage": "16,900 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9-Speed AMG SPEEDSHIFT TCT",
    "drivetrain": "4MATIC+ All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "603 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/1/19/Mercedes-AMG_GLE_63_S_4MATIC_IMG_3430.jpg",
    "desc": "Pristine condition Mercedes-AMG GLE 63 S sourced with verified history."
  },
  {
    "id": "006",
    "name": "GLE63",
    "fullName": "Mercedes-AMG GLE 63 S Coupe",
    "brand": "mercedes",
    "year": 2023,
    "mileage": "9,400 KM",
    "engine": "4.0L Twin-Turbo V8 + EQ Boost",
    "transmission": "9-Speed AMG SPEEDSHIFT TCT",
    "drivetrain": "4MATIC+ All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "603 hp",
    "torque": "850 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/96/2023_Mercedes-AMG_GLE_63_S_4MATIC_Coupe_IMG_0247.jpg",
    "desc": "Pristine condition Mercedes-AMG GLE 63 S Coupe sourced with verified history."
  },
  {
    "id": "007",
    "name": "VOGUE",
    "fullName": "Range Rover Autobiography P550 PHEV (L460)",
    "brand": "landrover",
    "year": 2023,
    "mileage": "7,200 KM",
    "engine": "4.4L Twin-Turbo V8 + Electric Motor",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol/Plug-in Hybrid",
    "power": "550 hp",
    "torque": "750 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Land_Rover_RANGE_ROVER_AUTOBIOGRAPHY_P550_AWD_PHEV_%28L460%29_front.jpg",
    "desc": "Pristine condition Range Rover Autobiography sourced with verified history."
  },
  {
    "id": "008",
    "name": "VOGUE",
    "fullName": "Range Rover D350 Autobiography LWB (L460)",
    "brand": "landrover",
    "year": 2023,
    "mileage": "11,500 KM",
    "engine": "3.0L Turbo I6 Diesel + Mild Hybrid",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Diesel/Hybrid",
    "power": "345 hp",
    "torque": "700 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/04/Land_Rover_Range_Rover_D350_Autobiography_L_L460_Belgravia_Green_%281%29.jpg",
    "desc": "Pristine condition Range Rover D350 Autobiography Long Wheelbase sourced with verified history."
  },
  {
    "id": "009",
    "name": "DISCO",
    "fullName": "Land Rover Discovery S (L462)",
    "brand": "landrover",
    "year": 2023,
    "mileage": "13,800 KM",
    "engine": "3.0L Turbo I6 Mild Hybrid",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol/Hybrid",
    "power": "395 hp",
    "torque": "550 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/b/bc/2023_Land_Rover_Discovery_S_in_Santorini_Black_Metallic%2C_front_right.jpg",
    "desc": "Pristine condition Land Rover Discovery sourced with verified history."
  },
  {
    "id": "010",
    "name": "DISCO",
    "fullName": "Land Rover Discovery TD6 HSE (L462)",
    "brand": "landrover",
    "year": 2016,
    "mileage": "54,300 KM",
    "engine": "3.0L Turbo V6 Diesel",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Diesel",
    "power": "254 hp",
    "torque": "600 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/b/b9/2016_Land_Rover_Discovery_TD6_HSE.jpg",
    "desc": "Pristine condition Land Rover Discovery TD6 HSE sourced with verified history. Strong value 7-seater family option."
  },
  {
    "id": "011",
    "name": "STI",
    "fullName": "Subaru Impreza WRX STI",
    "brand": "subaru",
    "year": 2014,
    "mileage": "61,200 KM",
    "engine": "2.5L Turbocharged Boxer (EJ257)",
    "transmission": "6-Speed Close-Ratio Manual",
    "drivetrain": "Symmetrical AWD with DCCD",
    "fuelType": "Petrol",
    "power": "300 hp",
    "torque": "407 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/04/Subaru_Impreza_WRX_STI_%28GV%29_IMG_5358.jpg",
    "desc": "Pristine condition Subaru WRX STI sourced with verified history."
  },
  {
    "id": "012",
    "name": "GT-R",
    "fullName": "Nissan GT-R Premium Edition (R35)",
    "brand": "nissan",
    "year": 2021,
    "mileage": "8,900 KM",
    "engine": "3.8L Twin-Turbo V6 (VR38DETT)",
    "transmission": "6-Speed Dual-Clutch",
    "drivetrain": "ATTESA E-TS AWD",
    "fuelType": "Petrol",
    "power": "565 hp",
    "torque": "633 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Nissan_GT-R_Premium_Edition_%28CBA-R35%29_front.JPG",
    "desc": "Pristine condition Nissan GT-R Premium Edition sourced with verified history."
  },
  {
    "id": "013",
    "name": "GT-R",
    "fullName": "Nissan GT-R Black Edition (R35)",
    "brand": "nissan",
    "year": 2020,
    "mileage": "17,400 KM",
    "engine": "3.8L Twin-Turbo V6 (VR38DETT)",
    "transmission": "6-Speed Dual-Clutch",
    "drivetrain": "ATTESA E-TS AWD",
    "fuelType": "Petrol",
    "power": "565 hp",
    "torque": "633 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/99/NISSAN_GT-R_%28R35%29_China.jpg",
    "desc": "Pristine condition Nissan GT-R Black Edition sourced with verified history."
  },
  {
    "id": "014",
    "name": "PRADO",
    "fullName": "Toyota Land Cruiser Prado TX (J150)",
    "brand": "toyota",
    "year": 2017,
    "mileage": "58,900 KM",
    "engine": "2.7L Petrol I4",
    "transmission": "6-Speed Automatic",
    "drivetrain": "Part-Time 4WD",
    "fuelType": "Petrol",
    "power": "163 hp",
    "torque": "246 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Toyota_land_cruiser_prado_2017.jpg",
    "desc": "Pristine condition Toyota Land Cruiser Prado TX sourced with verified history."
  },
  {
    "id": "015",
    "name": "PRADO",
    "fullName": "Toyota Land Cruiser Prado VX (J150)",
    "brand": "toyota",
    "year": 2011,
    "mileage": "97,300 KM",
    "engine": "4.0L Petrol V6",
    "transmission": "5-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "236 hp",
    "torque": "361 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/8/8d/2009-2011_Toyota_Land_Cruiser_Prado_%28KDJ150R%29_VX_5-door_wagon_%282011-10-25%29_01.jpg",
    "desc": "Pristine condition Toyota Land Cruiser Prado VX sourced with verified history. Higher-mileage value option."
  },
  {
    "id": "016",
    "name": "LX100",
    "fullName": "Toyota Land Cruiser 100 VXR (J100)",
    "brand": "toyota",
    "year": 2006,
    "mileage": "112,400 KM",
    "engine": "4.7L Petrol V8 (2UZ-FE)",
    "transmission": "5-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "235 hp",
    "torque": "427 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/94/Toyota_Land_Cruiser_100_50th_Anniversary_front.JPG",
    "desc": "Pristine condition Toyota Land Cruiser 100 VXR sourced with verified history. The legendary, bulletproof workhorse."
  },
  {
    "id": "017",
    "name": "LX570",
    "fullName": "Lexus LX570",
    "brand": "lexus",
    "year": 2009,
    "mileage": "89,700 KM",
    "engine": "5.7L Petrol V8",
    "transmission": "6-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "383 hp",
    "torque": "546 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/0c/2009_Lexus_LX570_DC.JPG",
    "desc": "Pristine condition Lexus LX570 sourced with verified history."
  },
  {
    "id": "018",
    "name": "LX570",
    "fullName": "Lexus LX570 Black Onyx (URJ200)",
    "brand": "lexus",
    "year": 2015,
    "mileage": "63,500 KM",
    "engine": "5.7L Petrol V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "Full-Time 4WD",
    "fuelType": "Petrol",
    "power": "383 hp",
    "torque": "546 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/5/56/Lexus_LX_570_URJ200_Black_Onyx_-_front.jpg",
    "desc": "Pristine condition Lexus LX570 Black Onyx sourced with verified history."
  },
  {
    "id": "019",
    "name": "X5M",
    "fullName": "BMW X5 M Competition (G05)",
    "brand": "bmw",
    "year": 2022,
    "mileage": "14,100 KM",
    "engine": "4.4L Twin-Turbo V8",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "M xDrive AWD",
    "fuelType": "Petrol",
    "power": "617 hp",
    "torque": "750 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/4/4e/BMW_X5_M_%28G05%29_1X7A7047.jpg",
    "desc": "Pristine condition BMW X5 M Competition sourced with verified history."
  },
  {
    "id": "020",
    "name": "CAYENNE",
    "fullName": "Porsche Cayenne Coupe Turbo",
    "brand": "porsche",
    "year": 2021,
    "mileage": "19,600 KM",
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Tiptronic S",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "541 hp",
    "torque": "770 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/96/Porsche_Cayenne_Coup%C3%A9_Turbo_%2848776650141%29.jpg",
    "desc": "Pristine condition Porsche Cayenne Coupe Turbo sourced with verified history."
  },
  {
    "id": "021",
    "name": "S500",
    "fullName": "Mercedes-Benz S500 4MATIC (W223)",
    "brand": "mercedes",
    "year": 2022,
    "mileage": "12,300 KM",
    "engine": "3.0L Turbo I6 + EQ Boost",
    "transmission": "9G-TRONIC Automatic",
    "drivetrain": "4MATIC All-Wheel Drive",
    "fuelType": "Petrol/Hybrid",
    "power": "429 hp",
    "torque": "520 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/4/45/Mercedes-Benz_S500_%28W223%29_Washington_DC_Metro_Area%2C_USA_%281%29.jpg",
    "desc": "Pristine condition Mercedes-Benz S500 sourced with verified history."
  },
  {
    "id": "022",
    "name": "RUBICON",
    "fullName": "Jeep Wrangler Rubicon (JL)",
    "brand": "jeep",
    "year": 2021,
    "mileage": "24,700 KM",
    "engine": "2.0L Turbo I4",
    "transmission": "8-Speed Automatic",
    "drivetrain": "Rock-Trac 4x4 System",
    "fuelType": "Petrol",
    "power": "270 hp",
    "torque": "400 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Jeep_Wrangler_Rubicon_2.0L_JL_Black_%281%29.jpg",
    "desc": "Pristine condition Jeep Wrangler Rubicon sourced with verified history."
  },
  {
    "id": "023",
    "name": "GOLF R",
    "fullName": "Volkswagen Golf R Mk8",
    "brand": "volkswagen",
    "year": 2022,
    "mileage": "10,900 KM",
    "engine": "2.0L Turbo I4 (EA888 Gen 4)",
    "transmission": "7-Speed DSG Dual-Clutch",
    "drivetrain": "4MOTION AWD with Torque Vectoring",
    "fuelType": "Petrol",
    "power": "315 hp",
    "torque": "420 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Volkswagen_Golf_VIII_R_333_Limited_Edition_IMG_9486.jpg",
    "desc": "Pristine condition Volkswagen Golf R sourced with verified history."
  },
  {
    "id": "024",
    "name": "HILUX",
    "fullName": "Toyota Hilux GR Sport 2.8 Double Cab",
    "brand": "toyota",
    "year": 2024,
    "mileage": "6,800 KM",
    "engine": "2.8L Turbo Diesel",
    "transmission": "6-Speed Automatic",
    "drivetrain": "Part-Time 4WD",
    "fuelType": "Diesel",
    "power": "204 hp",
    "torque": "500 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Toyota_Hilux_2.8_GR_Sport_4x4_2024_%281%29.jpg",
    "desc": "Pristine condition Toyota Hilux GR Sport sourced with verified history."
  },
  {
    "id": "025",
    "name": "M5",
    "fullName": "BMW M5 Competition (F90)",
    "brand": "bmw",
    "year": 2022,
    "mileage": "9,200 KM",
    "engine": "4.4L Twin-Turbo V8",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "M xDrive AWD",
    "fuelType": "Petrol",
    "power": "617 hp",
    "torque": "750 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/8/81/2022_BMW_M5_Competition_Red_F90.jpg",
    "desc": "Pristine condition BMW M5 Competition sourced with verified history."
  },
  {
    "id": "026",
    "name": "M5",
    "fullName": "BMW M5 Competition (F90)",
    "brand": "bmw",
    "year": 2018,
    "mileage": "41,500 KM",
    "engine": "4.4L Twin-Turbo V8",
    "transmission": "8-Speed M Steptronic",
    "drivetrain": "M xDrive AWD",
    "fuelType": "Petrol",
    "power": "617 hp",
    "torque": "750 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/1/19/2018_BMW_M5_Competition_in_Alpinwei%C3%9F%2C_front_left.jpg",
    "desc": "Pristine condition BMW M5 Competition sourced with verified history. Strong value entry into M5 ownership."
  },
  {
    "id": "027",
    "name": "SVR",
    "fullName": "Range Rover Sport SVR (L494)",
    "brand": "landrover",
    "year": 2016,
    "mileage": "46,800 KM",
    "engine": "5.0L Supercharged V8",
    "transmission": "8-Speed Automatic",
    "drivetrain": "All-Wheel Drive (AWD)",
    "fuelType": "Petrol",
    "power": "543 hp",
    "torque": "680 Nm",
    "img": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Osaka_Motor_Show_2015_%28389%29_-_Land_Rover_RANGE_ROVER_SPORT_SVR_%28L494%29.JPG",
    "desc": "Pristine condition Range Rover Sport SVR sourced with verified history."
  }
];
 